### ISSUE TITLE
Cache subqueries

### ISSUE THREAD

**Issue by vsopko** [VahidN/EFSecondLevelCache.Core#30]
It may be cool, unique feauture to populate cache while enumerating related subqueries like this:
~~~
var query = context.DataSetA.Select(a => new
{
    prop1 = a.prop1,
    prop2 = context.DataSetB.Where(b => b.Id == a.Id).Cacheable().Select(b => new
    {
         b.prop2
    })
})
~~~

**Comment by VahidN** [comment]
Defining a sub-query here is meaningless. Because the second level cache is disconnected from the context and it will read the result from the cache, not from the context and its related database. When you are using a the second level cache, the EF's query parser can't translate this part to an SQL and produce a single SQL statement for the outer and inner queries, because at the end it's an in-memory result and completely disconnect from the context.
So convert your sub-query to an independent query and then use its result.

**Comment by vsopko** [comment]
@VahidN, I understand that you simply get result SQL and hash from it, but it would be great to be able to cache joined or subquery entities or collections. Now there is no caching solutions for applications more complex then brick, where some complex data changes frequently and some not. For example realty where for each entity we have address. There is no sense to cache all entities with relations, because frequent cache invalidation kills the aim of cache, and also there is no sense to cache billions of addresses, because often requested is only small part of them. And also i think that it is possible to get required SQL to get hash for it. The only thing is to modify Cacheable extension logic with EF Core tightly integration. EF Core has enought placess to hookup and get all you need to get a result. QueryCompiler, where you can modify expressions, SelectExpression and QuerySqlGeneratorFactory, where you can get all the required data, while visiting result expression for left joined and inner joined tables.
@SteffenMangold what do you think about this? I see that you quickly launched some improvements for this library and studied the issue of EF Core SQL generation (waiting for integration with Redis with your implementation)
