### ISSUE TITLE
Caching expressions with "string.Equals()" does not work

### ISSUE THREAD

**Issue by maximgorbatyuk** [VahidN/EFSecondLevelCache.Core#33]
If we cache an expression that contains `string.Equals(string)`, a result will be the same even any kind of string value would be passed as arguments. But a way `string == string` works.

**Comment by VahidN** [comment]
[I added a test for it](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/Tests/EFSecondLevelCache.Core.AspNetCoreSample/Controllers/HomeController.cs#L54) and I can't reproduce it. `IsCacheHit` is always `false` here, which means it doesn't read the value from the cache, when it's using different random values.

**Comment by maximgorbatyuk** [comment]
Sorry for late response, @VahidN .
I have tried some ways to reproduce an it seems like the bug will appear when I use "Invariant" comparing.
Look to the screenshots below:
When I use `string.Equals("ololo", InvariantCultureIgnoreCase) the bug appears:
![reproduced bug](https://user-images.githubusercontent.com/13348685/52543701-dc5ee000-2dd5-11e9-9e0d-1de574bad8b4.png)

When I use `string.ToUpperInvariant() == string.ToUpperInvariant()` the bug appears:
![reproduced upper](https://user-images.githubusercontent.com/13348685/52543729-01ebe980-2dd6-11e9-9e5d-70a4e659fb02.png)

When I use just `string.Lower() == string.Lower()` the bug does not appear:
![all is ok lower](https://user-images.githubusercontent.com/13348685/52543743-25af2f80-2dd6-11e9-9383-0bd3f38ea297.png)

Here is a piece of code to make yor way to reproduce the bug more easy: https://gist.github.com/maximgorbatyuk/4a48e227e7f47d3097860b58678059f0

**Comment by VahidN** [comment]
You should start reading about `Collations`. When you are working with for instance the SQL Server, you don't need to use `ToUpper` or `ToLower` in your queries. Why? Because the SQL Server will use its current `Collation` to handle it. [more info](https://www.red-gate.com/simple-talk/sql/sql-development/questions-sql-server-collations-shy-ask/)
- When you are using `ToUpperInvariant` in your Linq to Entities queries, EF will switch to the `client side evaluation` to handle it. in this case, you think it will add your parameters to the final SQL, but it won't. It will create a general SQL without any parameters and then it will filter on the client side. that's why you will see that behavior. [More info](https://docs.microsoft.com/en-us/ef/core/querying/client-eval).
- [You should can add](https://docs.microsoft.com/en-us/ef/core/querying/client-eval#optional-behavior-throw-an-exception-for-client-evaluation) `ConfigureWarnings(warnings => warnings.Throw(RelationalEventId.QueryClientEvaluationWarning)` to your EF Core settings to see which queries are being evaluated on the client, not on the server.

**Comment by maximgorbatyuk** [comment]
Oh, thank you for links to the materials. 
We use PostgresQL instead of MSSQL server.
So, to make it clear, we should use just `.Where(x => x.Title == title)` to search with insensitive case in LinqToSql even `title` has some kind of  "pOsT1"value, isn't it?

**Comment by VahidN** [comment]
- [PostgreSQL is different](https://stackoverflow.com/questions/18807276/how-to-make-my-postgresql-database-use-a-case-insensitive-collation) than SQL Server and you [will need tolower for it](https://stackoverflow.com/questions/7005302/postgresql-how-to-make-case-insensitive-query).
- In this case, use methods that are not being evaluated on the client side and can be translated to SQL (for performance reasons and for better caching).
- If you insist to use the `client side evaluation`, you can use the [saltKey parameter](https://github.com/VahidN/EFSecondLevelCache.Core/blob/master/src/EFSecondLevelCache.Core/EFCachedQueryExtensions.cs#L22), to change the final hash and make it unique.
- But remember, LINQ to Entities queries are different than LINQ to Object queries, because of the `Collation` concept.

**Comment by maximgorbatyuk** [comment]
Thank you for explanation of background!
